### ISSUE TITLE
Introducing 'PRODIGy: A PROfile-based DIalogue Generation Dataset' Paper

### ISSUE THREAD

**Issue by danie08** [MiuLab/PersonaLLM-Survey#2]
Hi! Congratulations on your awesome work! 

I would like to bring to your attention our paper, "PRODIGy: A PROfile-based DIalogue Generation Dataset," which has been accepted for publication at NAACL 2024. We believe our research might be highly relevant to your work. In this work, we introduce a dataset comprising over 20,000 dialogues extracted from movie scripts, each aligned with detailed speaker profiles. These profiles include communication style (an implicit persona representation), biography, personality, and gender (explicit persona representations), providing a comprehensive set of profile dimensions for each speaker.

Here's the link to the paper: https://aclanthology.org/2024.findings-naacl.222/.

We would be grateful if you could consider adding our paper to your repository and including it in your survey paper.

Thank you very much for your time and effort!

**Comment by ymntseng** [comment]
Thanks for reaching out and congrats on your NAACL 2024 paper! PRODIGy looks highly relevant with our paper, and we’d be happy to include it in the next version of the survey paper and the following update of our repository!

Appreciate you sharing it with us :-)
